import { createClient } from '@supabase/supabase-js';

// Supabase credentials loaded from Vite environment variables (.env file)
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

// Initialize client if credentials are provided
export const supabase = supabaseUrl && supabaseAnonKey 
  ? createClient(supabaseUrl, supabaseAnonKey) 
  : null;

// ── Auth Helpers ──────────────────────────────────────────────
export const signIn = (email, password) =>
  supabase?.auth.signInWithPassword({ email, password });

export const signOut = () =>
  supabase?.auth.signOut();

export const getSession = () =>
  supabase?.auth.getSession();

export const onAuthStateChange = (callback) =>
  supabase?.auth.onAuthStateChange(callback);


/**
 * =========================================================================
 * 🛠️ SUPABASE DATABASE SETUP INSTRUCTIONS
 * =========================================================================
 * 
 * Silakan salin dan jalankan skrip SQL di bawah ini di SQL Editor Supabase Anda 
 * untuk membuat tabel `aspirations` yang siap digunakan oleh website ini:
 * 
 * -------------------------------------------------------------------------
 * -- 1. Buat Tabel Aspirasi
 * CREATE TABLE public.aspirations (
 *     id bigint generated by default as identity primary key,
 *     created_at timestamp with time zone default timezone('utc'::text, now()) not null,
 *     name text not null,
 *     phone text not null,
 *     kecamatan text not null,
 *     category text not null,
 *     subject text not null,
 *     detail text not null,
 *     status text default 'received'::text not null, -- 'received', 'processing', 'done'
 *     response text,
 *     date date default current_date not null
 * );
 * 
 * -- 2. Aktifkan Row Level Security (RLS)
 * ALTER TABLE public.aspirations ENABLE ROW LEVEL SECURITY;
 * 
 * -- 3. Buat Kebijakan RLS (RLS Policies)
 * -- Kebijakan A: Izinkan siapa saja (publik/anonim) untuk melihat data aspirasi
 * CREATE POLICY "Izinkan publik membaca aspirasi" 
 * ON public.aspirations 
 * FOR SELECT 
 * USING (true);
 * 
 * -- Kebijakan B: Izinkan siapa saja (publik/anonim) untuk mengirim aspirasi baru
 * CREATE POLICY "Izinkan publik mengirim aspirasi" 
 * ON public.aspirations 
 * FOR INSERT 
 * WITH CHECK (true);
 * 
 * -- Kebijakan C: Izinkan admin yang terautentikasi untuk memperbarui data (status & tindak lanjut)
 * CREATE POLICY "Izinkan admin mengubah aspirasi" 
 * ON public.aspirations 
 * FOR UPDATE 
 * TO authenticated 
 * USING (true) 
 * WITH CHECK (true);
 * 
 * -- 4. Masukkan Data Bawaan Awal (Opsional)
 * INSERT INTO public.aspirations (name, phone, kecamatan, category, subject, detail, status, response, date)
 * VALUES 
 * ('Ahmad Fauzi', '08123456789', 'Kec. Maju Jaya', 'Infrastruktur', 'Jalan Rusak & Berlumpur', 'Jalan poros desa sepanjang 2 km berlubang parah dan berlumpur saat hujan, menyulitkan akses anak sekolah.', 'done', 'Perbaikan jalan desa sepanjang 2 km telah rampung dikerjakan menggunakan APBD Perubahan 2024.', '2024-11-20'),
 * ('Ibu Ratna', '08129876543', 'Kec. Sejahtera', 'Pendidikan', 'Beasiswa Anak Yatim Piatu', 'Banyak anak yatim piatu terancam putus sekolah karena keterbatasan biaya buku dan seragam sekolah.', 'done', 'Beasiswa bekerjasama dengan CSR perusahaan telah disalurkan untuk 15 anak yatim piatu di Kel. Sejahtera.', '2024-12-05'),
 * ('Bapak Hendra', '08134567890', 'Kec. Harapan Baru', 'Kesehatan', 'Puskesmas Pembantu Tidak Aktif', 'Puskesmas pembantu Dusun Harapan sudah 3 bulan tidak ada tenaga medis yang bertugas, menyulitkan berobat.', 'processing', 'Sedang dikoordinasikan dengan Dinas Kesehatan untuk penempatan tenaga medis/bidan desa baru.', '2025-01-10');
 * -------------------------------------------------------------------------
 */
